[tool.poetry]
name = "pdftxt"
version = "0.1.0"
description = ""
authors = ["Robin Harvey <harvey.robin@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
structlog = "^22.3.0"

[tool.poetry.dev-dependencies]
black = {version = "^22.12.0", allow-prereleases = true}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
